### ISSUE TITLE
netstandard2.1 compiling error: CS8987 The ‘scoped’ modifier of parameter ‘value’ doesn’t match overridden or implemented member

### ISSUE THREAD

**Issue by xiaoyuvax** [Cysharp/MemoryPack#55]
when work with netstandard2.1, the compiler reports on the generated code:
CS8987 The ‘scoped’ modifier of parameter ‘value’ doesn’t match overridden or implemented member.

how to solve this and get MemoryPack work with netstandard2.1?  
since i've already dual-targeted both netstandard2.1 and net7.0, and this compiler error prevents my netstandard2.1 library to be compiled.
```
partial class Stat
{
    [global::MemoryPack.Internal.Preserve]
    sealed class StatFormatter : MemoryPackFormatter<Stat>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref Stat value)            <-- here
        {
            Stat.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref Stat value)           <-- and here
        {
            Stat.Deserialize(ref reader, ref value);
        }
    }
}
```

**Comment by neuecc** [comment]
Thank you for reporting.
can't compile when targetframework is netstandard2.1 and C#11 environment, it is a bug.
I've fixed and released at `1.7.7`, please try it.

**Comment by xiaoyuvax** [comment]
Tested positive! thanks for light speed, lol
but seems still requires dual-trageting in case of netstandard2.1 lib using 2.1lib, where 
 CS8920 "The interface ‘{0}’ cannot be used as type argument. Static member ‘{1}’ does not have a most specific implementation in the interface." still cannot be solved?

**Comment by neuecc** [comment]
Yes, I wrote about that just yesterday.
https://github.com/Cysharp/MemoryPack#target-framework-dependency

.NET 7 and .NET Standard 2.1 are not compatible.
Because static abstract members are a feature that requires a .NET 7 runtime update, and are the basis for performance in .NET 7 version of MemoryPack.
The 2.1lib is only to support net6 (and Unity) and is close to being a separate product.
This is a temporary measure as we believe this situation will not be a problem once net8 (LTS) is released.

**Comment by xiaoyuvax** [comment]
I saw that remarks but not quite understand its implication, for i had thought 2.1 libs may work with net7 consumers somehow and that'll be great for my legacy projects. 
Now i know it, i.e. MemoryPack DOES NOT Support NET versions other than 7.0, but Dual-targeting netstandard2.1 makes the compile Pass, -ONLY, and it doesn't mean u can consume MemoryPack in 2.1 libs. LOL 

i think u may add a line like this for a better explanation. ;-)

**Comment by neuecc** [comment]
I agree, added more:)
